### ISSUE TITLE
window.crypto.subtle is undefined?

### ISSUE THREAD

**Issue by kevzettler** [vector-im/hydrogen-web#933]
**Describe the bug**

getting an error on my production domain that uses hydrogen.

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'deriveBits')
    at new MD (hydrogen.es.js:7501:23)
    at new oO (hydrogen.es.js:8721:21)
    at XF (HydrogenRootView.tsx:161:20)
    at Object.Qs [as useState] (react-dom.production.min.js:165:102)
    at X.useState (react.production.min.js:23:281)
    at nB (HydrogenRootView.tsx:404:78)
    at lp (react-dom.production.min.js:157:137)
    at mb (react-dom.production.min.js:267:460)
    at hb (react-dom.production.min.js:250:347)
    at uT (react-dom.production.min.js:250:278)
```

The hydrogen.es.js line comes from the implementation of this `Crypto` class

```
class Crypto {
  constructor(cryptoExtras) {
    const crypto2 = window.crypto || window.msCrypto;
    const subtleCrypto = crypto2.subtle || crypto2.webkitSubtle;
    this._subtleCrypto = subtleCrypto;
    if (!subtleCrypto.deriveBits && (cryptoExtras == null ? void 0 : cryptoExtras.aesjs)) {
      this.aes = new AESLegacyCrypto(cryptoExtras.aesjs, crypto2);
    } else {
      this.aes = new AESCrypto(subtleCrypto, crypto2);
    }
    this.hmac = new HMACCrypto(subtleCrypto);
    this.derive = new DeriveCrypto(subtleCrypto, this, cryptoExtras);
  }
 ```
 
 If I log from the browser console This `subtle` property is not defined
 
<img width="694" alt="image" src="https://user-images.githubusercontent.com/126209/202052028-c2e13cf8-07c2-456b-a73b-63dfef370ba9.png">

I can host the same static HTML/JS code on localhost and this error doesn't happen.

**Desktop (please complete the following information):**
 - Linux crashgiants 4.15.0-196-generic #207-Ubuntu SMP Thu Oct 27 21:24:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - [Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)](https://brave.com/latest/)

**Additional context**
This is specifically stemming from fork package
`    "@thirdroom/hydrogen-view-sdk": "0.0.27",`

**Comment by kevzettler** [comment]
Seems this is a secure context http(s) related issue

**Comment by missmah** [comment]
Why closed as completed? I'm seeing the same error. If the answer is "you must access via https://" then being more explicit about that might help people :)

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto (Link describing the necessity to access via secure contexts HTTPS)

For anyone else who hits this issue, you must access the page via https:// for this code to work properly. It's pretty terrible that there is no check for that which just spits out "ERROR: You must access the page via https:// for this code to work properly!" - instead of crashing with a `TypeError r undefined` deep inside `hydrogen.es.js`...

Is there an `assert` we can do on `https` far before the code gets to this point?
